version: 1.0.{build}

environment:
  matrix:
  - PLATFORM: mingw64
  - PLATFORM: cygwin64

install:
  - call %APPVEYOR_BUILD_FOLDER%\install.bat
  
build_script:
  - call %APPVEYOR_BUILD_FOLDER%\build_script.bat

after_build:
  - call %APPVEYOR_BUILD_FOLDER%\after_build.bat

test_script:
  - 'echo skip test'
  
artifacts:
  - path: swift_foundation.zip
    name: SWIFT FOUNDATION
