version: 1.0.{build}

environment:
  matrix:
  - BUILD_TARGET: mingw64
  - BUILD_TARGET: cygwin64

install:
  - call %APPVEYOR_BUILD_FOLDER%\install_%BUILD_TARGET%.bat
  
build_script:
  - call %APPVEYOR_BUILD_FOLDER%\build_script_%BUILD_TARGET%.bat

after_build:
  - call %APPVEYOR_BUILD_FOLDER%\after_build_%BUILD_TARGET%.bat

test_script:
  - 'echo skip test'
  
artifacts:
  - path: swift_foundation.zip
    name: SWIFT FOUNDATION
