version: 1.0.{build}

environment:
  matrix:
  - TARGET_BUILD: mingw64
  - TARGET_BUILD: cygwin64

install:
  - call %APPVEYOR_BUILD_FOLDER%\install_%TARGET_BUILD%.bat
  
build_script:
  - call %APPVEYOR_BUILD_FOLDER%\build_script_%TARGET_BUILD%.bat

after_build:
  - call %APPVEYOR_BUILD_FOLDER%\after_build_%TARGET_BUILD%.bat

test_script:
  - 'echo skip test'
  
artifacts:
  - path: swift_foundation.zip
    name: SWIFT FOUNDATION
